// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace newTest.Data.newTest
{
    public partial class CompanydirectoryContext : DbContext
    {
        public CompanydirectoryContext()
        {
        }

        public CompanydirectoryContext(DbContextOptions<CompanydirectoryContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PersonnelNew> PersonnelNew { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<PersonnelNew>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.Property(e => e.Email).IsUnicode(false);

                entity.Property(e => e.FirstName).IsUnicode(false);

                entity.Property(e => e.JobTitle).IsUnicode(false);

                entity.Property(e => e.LastName).IsUnicode(false);

                entity.Property(e => e.UserName).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}